"""add is_intro_question to questions

Revision ID: f16d90513318
Revises: 7e29a1ff3d89
Create Date: 2026-07-28 17:11:16.289266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16d90513318'
down_revision: Union[str, Sequence[str], None] = '7e29a1ff3d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_intro_question', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_intro_question')
    # ### end Alembic commands ###
